name: sari-tebu-production
services:
    database:
        image: mysql:8.4
        container_name: sari-tebu-database
        restart: always
        env_file:
            - .env.prod
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 20s
            retries: 10
            start_period: 30s

    server:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.prod
        ports:
            - "${HOST}${PORT:-8080}:${PORT:-8080}"
        depends_on:
            database:
                condition: service_healthy

volumes:
    mysql_data: