FROM node:22-alpine 

USER node
WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
RUN npm ci --omit=dev

COPY --chown=node:node prisma prisma.config.js ./
RUN npx prisma generate

COPY --chown=node:node . .

CMD ["npm", "run", "start"]